repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        args: [--unsafe]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements

  - repo: local
    hooks:
      - id: python-compile
        name: python-compile
        entry: python3 -m py_compile
        language: system
        types: [python]
